/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package alvian_ukk;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author Lenovo-ZA
 */
public class pengembalian extends javax.swing.JFrame {
        Connection conn = null;
        ResultSet rs = null;
        PreparedStatement pst = null;
    /**
     * Creates new form pengembalian
     */
    public pengembalian() {
        initComponents();
         try {
           conn = koneksi.koneksi();
           tampilkan_data();
           t_listdata();
       } catch (SQLException ex) {
           System.out.println("Form Tidak Dapat Terkoneksi");
       }
    }
    private void tampilkan_data(){
        
       String perintah = "SELECT * FROM peminjaman";
        
       try {
            pst = conn.prepareStatement(perintah);
            rs = pst.executeQuery();
            DefaultTableModel tbarang = new DefaultTableModel();
            tbarang.addColumn("ID peminjaman");
            tbarang.addColumn("Nama");
            tbarang.addColumn("No Tlp");
            tbarang.addColumn("Status");
            tbarang.addColumn("Tanggal Peminjaman");
            tbarang.addColumn("Ruangan");

            while (rs.next()){

                tbarang.addRow(
                     new Object[]{
                         rs.getString(1), 
                         rs.getString(2), 
                         rs.getString(3),
                         rs.getString(4),
                         rs.getString(5),
                         rs.getString(6)
                     });

            }
            jpeminjaman.setModel(tbarang);
           
           }
       
       catch (SQLException ex) {
           System.out.println("Tidak Dapat Menapilkan");
       }


    }
    
    private void t_listdata(){
        String statement = "SELECT * FROM inventaris";
        
        try {
            pst = conn.prepareStatement(statement);
            rs = pst.executeQuery();
            DefaultTableModel listbarang = new DefaultTableModel();
            listbarang.addColumn("ID Barang");
            listbarang.addColumn("Nama Barang");
            listbarang.addColumn("Jumlah");
            while (rs.next()){

                listbarang.addRow(
                     new Object[]{
                         rs.getString(1), 
                         rs.getString(2), 
                         rs.getString(3),
              });
                        
            }
            jlis.setModel(listbarang);
        } catch (SQLException ex) {
            Logger.getLogger(pinjem.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jdate = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jno = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        js = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jpeminjaman = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        namabarang = new javax.swing.JTextField();
        jjumlah = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jruangan = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jnama = new javax.swing.JTextField();
        jid = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jlis = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setText("PENGEMBALIAN");

        jLabel5.setText("Tanggal Minjam");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel9.setText("BARANG");

        jLabel10.setText("Nama Barang");

        jLabel11.setText("Jumlah");

        jpeminjaman.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jpeminjaman);

        jButton1.setText("Input");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        namabarang.setEditable(false);

        jjumlah.setEditable(false);

        jLabel1.setText("Nama Peminjam");

        jLabel8.setText("Ruangan");

        jLabel3.setText("No Telphone");

        jLabel12.setText("ID Peminjam");

        jid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jidActionPerformed(evt);
            }
        });

        jLabel4.setText("Status");

        jlis.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "null"
            }
        ));
        jlis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlisMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jlis);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addContainerGap(824, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5)
                                .addComponent(jLabel4)
                                .addComponent(jLabel3)
                                .addComponent(jLabel1)
                                .addComponent(jLabel12)
                                .addComponent(jLabel8)
                                .addComponent(jLabel9)
                                .addComponent(jLabel10)
                                .addComponent(jLabel11))
                            .addGap(59, 59, 59)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jnama)
                                .addComponent(jno)
                                .addComponent(js)
                                .addComponent(jdate, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                                .addComponent(jruangan)
                                .addComponent(jid)
                                .addComponent(namabarang)
                                .addComponent(jjumlah, javax.swing.GroupLayout.Alignment.TRAILING)))
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 705, Short.MAX_VALUE)
                        .addComponent(jScrollPane2))
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel6)
                .addContainerGap(444, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(58, 58, 58)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel12)
                                .addComponent(jid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(15, 15, 15)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel1)
                                .addComponent(jnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(21, 21, 21)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(js, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5))
                            .addGap(26, 26, 26)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel8)
                                .addComponent(jruangan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(31, 31, 31)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel9)
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel10)
                                .addComponent(namabarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jjumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel11))
                            .addGap(39, 39, 39)
                            .addComponent(jButton1))
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //query insert peminjaman
        String perintah = "INSERT INTO peminjaman ( id_peminjaman, nama_peminjaman, no_tlp, status, tgl_peminjaman, ruangan) VALUES(?,?,?,?,?,?)";
        SimpleDateFormat sdf = new SimpleDateFormat ("yyy-MM-dd");
        //query insert detail_peminjaman
        String perintah2 = "INSERT INTO detail_peminjaman ( id_peminjaman, id_inventaris, jumlah) VALUES (?,?,?)";
        //query update inventaris
        String perintah3 = "UPDATE inventaris set jumlah = ? WHERE id_inventaris = ?";
        //select untuk inventaris
        String dara = "SELECT * FROM inventaris WHERE nama = '"+namabarang.getText()+"'";
        int jumlah = Integer.parseInt(jjumlah.getText());

        try {
            PreparedStatement psi = conn.prepareStatement(perintah2);
            PreparedStatement pse = conn.prepareStatement(perintah3);
            PreparedStatement id_i = conn.prepareStatement(dara);
            rs = id_i.executeQuery();
            rs.next();
            int id = Integer.parseInt(rs.getString("jumlah")) ;
            int hasil = id - jumlah;
            System.out.println(hasil);
            //jika barang tersedia atau tidak
            if (hasil < 0 )
            {

                JOptionPane.showMessageDialog(null, "BArang telah habis");

            }
            else {
                pst = conn.prepareStatement(perintah);
                //insert ke table peminjaman
                pst.setString(1, jid.getText());
                pst.setString(2, jnama.getText());
                pst.setString(3, jno.getText());
                pst.setString(4, js.getText());
                String tgl = sdf.format(jdate.getDate());
                pst.setString(5, tgl);
                pst.setString(6, jruangan.getText());

                //insert ke table detail peminjaman
                psi.setString(1,jid.getText() );
                psi.setString(2, rs.getString("id_inventaris"));
                psi.setString(3, jjumlah.getText());

                //update jumlah di inventaris
                pse.setInt(1, hasil);
                pse.setString(2,  rs.getString("id_inventaris"));

                JOptionPane.showMessageDialog(null, "Data berhasil masuk");
                pst.execute();
                psi.execute();
                pse.execute();
                tampilkan_data();
                t_listdata();
            }

        } catch (SQLException ex) {
            //Logger.getLogger(Sparepart.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jidActionPerformed

    private void jlisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlisMouseClicked
        // TODO add your handling code here:
        int row = jlis.getSelectedRow();
        String diklik = (jlis.getModel().getValueAt(row,0).toString());
        String perintah = "SELECT * FROM inventaris WHERE id_inventaris = '"+diklik+"' ";

        try {
            pst = conn.prepareStatement(perintah);
            rs = pst.executeQuery();

            if(rs.next()){
                String text1 = rs.getString("nama");
                namabarang.setText(text1);
            }

        }

        catch (SQLException ex) {
            // Logger.getLogger(Sparepart.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jlisMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pengembalian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pengembalian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pengembalian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pengembalian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pengembalian().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private com.toedter.calendar.JDateChooser jdate;
    private javax.swing.JTextField jid;
    private javax.swing.JTextField jjumlah;
    private javax.swing.JTable jlis;
    private javax.swing.JTextField jnama;
    private javax.swing.JTextField jno;
    private javax.swing.JTable jpeminjaman;
    private javax.swing.JTextField jruangan;
    private javax.swing.JTextField js;
    private javax.swing.JTextField namabarang;
    // End of variables declaration//GEN-END:variables
}
